
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE cars (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    make text NOT NULL,
    model text NOT NULL,
    year integer NOT NULL,
    vin text NOT NULL,
    color text NOT NULL,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20220826034927_PosresSnakeCase', '6.0.8');

COMMIT;


